- name: 安装zabbix源
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
    validate_certs: false

- name: 安装zabbix-agent
  yum:
    name: zabbix-agent
